// Mocks generated by Mockito 5.4.6 from annotations
// in breathe_flow/test/profile_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;
import 'dart:typed_data' as _i8;
import 'dart:ui' as _i12;

import 'package:breathe_flow/models/mood_type.dart' as _i10;
import 'package:breathe_flow/models/weekly_activity.dart' as _i3;
import 'package:breathe_flow/providers/user_preferences_provider.dart' as _i9;
import 'package:breathe_flow/services/auth_service.dart' as _i4;
import 'package:breathe_flow/services/notification_service.dart' as _i13;
import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTimeOfDay_0 extends _i1.SmartFake implements _i2.TimeOfDay {
  _FakeTimeOfDay_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeeklySummary_1 extends _i1.SmartFake implements _i3.WeeklySummary {
  _FakeWeeklySummary_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.User?> get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _i5.Stream<_i6.User?>.empty(),
          )
          as _i5.Stream<_i6.User?>);

  @override
  _i5.Future<_i6.UserCredential?> signUpWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [email, password]),
            returnValue: _i5.Future<_i6.UserCredential?>.value(),
          )
          as _i5.Future<_i6.UserCredential?>);

  @override
  _i5.Future<_i6.UserCredential?> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i5.Future<_i6.UserCredential?>.value(),
          )
          as _i5.Future<_i6.UserCredential?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> uploadProfilePhoto(_i7.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [imageFile]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> uploadProfilePhotoBytes(_i8.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhotoBytes, [imageBytes]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> deleteProfilePhoto() =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfilePhoto, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [currentPassword, newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [password]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> userExistsInFirestore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#userExistsInFirestore, [uid]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> createMissingUserRecord() =>
      (super.noSuchMethod(
            Invocation.method(#createMissingUserRecord, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UserPreferencesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserPreferencesProvider extends _i1.Mock
    implements _i9.UserPreferencesProvider {
  MockUserPreferencesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get notificationsEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i2.TimeOfDay get reminderTime =>
      (super.noSuchMethod(
            Invocation.getter(#reminderTime),
            returnValue: _FakeTimeOfDay_0(
              this,
              Invocation.getter(#reminderTime),
            ),
          )
          as _i2.TimeOfDay);

  @override
  int get dailyGoalMinutes =>
      (super.noSuchMethod(Invocation.getter(#dailyGoalMinutes), returnValue: 0)
          as int);

  @override
  _i10.MoodType get preferredMood =>
      (super.noSuchMethod(
            Invocation.getter(#preferredMood),
            returnValue: _i10.MoodType.relaxation,
          )
          as _i10.MoodType);

  @override
  bool get isFirstLaunch =>
      (super.noSuchMethod(Invocation.getter(#isFirstLaunch), returnValue: false)
          as bool);

  @override
  int get totalSessions =>
      (super.noSuchMethod(Invocation.getter(#totalSessions), returnValue: 0)
          as int);

  @override
  int get totalMinutes =>
      (super.noSuchMethod(Invocation.getter(#totalMinutes), returnValue: 0)
          as int);

  @override
  int get currentStreak =>
      (super.noSuchMethod(Invocation.getter(#currentStreak), returnValue: 0)
          as int);

  @override
  List<String> get favoriteExerciseIds =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteExerciseIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get favoriteSoundIds =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteSoundIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i9.MindfulSessionType get lastSessionType =>
      (super.noSuchMethod(
            Invocation.getter(#lastSessionType),
            returnValue: _i9.MindfulSessionType.none,
          )
          as _i9.MindfulSessionType);

  @override
  _i3.WeeklySummary get weeklySummary =>
      (super.noSuchMethod(
            Invocation.getter(#weeklySummary),
            returnValue: _FakeWeeklySummary_1(
              this,
              Invocation.getter(#weeklySummary),
            ),
          )
          as _i3.WeeklySummary);

  @override
  bool get isDailyGoalCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#isDailyGoalCompleted),
            returnValue: false,
          )
          as bool);

  @override
  double get dailyGoalProgress =>
      (super.noSuchMethod(
            Invocation.getter(#dailyGoalProgress),
            returnValue: 0.0,
          )
          as double);

  @override
  String get streakText =>
      (super.noSuchMethod(
            Invocation.getter(#streakText),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#streakText),
            ),
          )
          as String);

  @override
  String get totalTimeText =>
      (super.noSuchMethod(
            Invocation.getter(#totalTimeText),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#totalTimeText),
            ),
          )
          as String);

  @override
  int get longestStreak =>
      (super.noSuchMethod(Invocation.getter(#longestStreak), returnValue: 0)
          as int);

  @override
  int get dailyGoal =>
      (super.noSuchMethod(Invocation.getter(#dailyGoal), returnValue: 0)
          as int);

  @override
  int get weeklyGoal =>
      (super.noSuchMethod(Invocation.getter(#weeklyGoal), returnValue: 0)
          as int);

  @override
  int get todaySessionsCount =>
      (super.noSuchMethod(
            Invocation.getter(#todaySessionsCount),
            returnValue: 0,
          )
          as int);

  @override
  int get completedSessionsThisWeek =>
      (super.noSuchMethod(
            Invocation.getter(#completedSessionsThisWeek),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  bool isFavoriteExercise(String? exerciseId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavoriteExercise, [exerciseId]),
            returnValue: false,
          )
          as bool);

  @override
  bool isFavoriteSound(String? soundId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavoriteSound, [soundId]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> setNotificationsEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationsEnabled, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setReminderTime(_i2.TimeOfDay? time) =>
      (super.noSuchMethod(
            Invocation.method(#setReminderTime, [time]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setDailyGoalMinutes(int? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#setDailyGoalMinutes, [minutes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setPreferredMood(_i10.MoodType? mood) =>
      (super.noSuchMethod(
            Invocation.method(#setPreferredMood, [mood]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setFirstLaunchCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#setFirstLaunchCompleted, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recordSession(int? durationMinutes) =>
      (super.noSuchMethod(
            Invocation.method(#recordSession, [durationMinutes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#resetStatistics, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setDailyGoal(int? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#setDailyGoal, [minutes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetAllData() =>
      (super.noSuchMethod(
            Invocation.method(#resetAllData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recordHrvSession(int? score) =>
      (super.noSuchMethod(
            Invocation.method(#recordHrvSession, [score]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recordSleepSession(double? durationHours) =>
      (super.noSuchMethod(
            Invocation.method(#recordSleepSession, [durationHours]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recordBreathingSession(int? durationMinutes) =>
      (super.noSuchMethod(
            Invocation.method(#recordBreathingSession, [durationMinutes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recordSoundSession(int? durationMinutes) =>
      (super.noSuchMethod(
            Invocation.method(#recordSoundSession, [durationMinutes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleFavoriteExercise(String? exerciseId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavoriteExercise, [exerciseId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleFavoriteSound(String? soundId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavoriteSound, [soundId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllFavorites, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i13.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get notificationsEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> checkNotificationsEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#checkNotificationsEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> scheduleDailyBreathingReminder({
    required int? hour,
    required int? minute,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleDailyBreathingReminder, [], {
              #hour: hour,
              #minute: minute,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleDailySleepReminder({
    required int? hour,
    required int? minute,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleDailySleepReminder, [], {
              #hour: hour,
              #minute: minute,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelReminder(int? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelReminder, [notificationId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllReminders() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllReminders, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setNotificationsEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setNotificationsEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> showTestNotification({
    String? title = 'Breathe Flow Test',
    String? body = 'Bildirim sistemi çalışıyor! 🎉',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showTestNotification, [], {
              #title: title,
              #body: body,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
