// Mocks generated by Mockito 5.4.6 from annotations
// in breathe_flow/test/sleep_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:breathe_flow/core/analytics/analytics_service.dart' as _i2;
import 'package:breathe_flow/core/crashlytics/crashlytics_service.dart' as _i5;
import 'package:firebase_analytics/firebase_analytics.dart' as _i3;
import 'package:firebase_crashlytics/firebase_crashlytics.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i2.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  set analytics(_i3.FirebaseAnalytics? value) => super.noSuchMethod(
    Invocation.setter(#analytics, value),
    returnValueForMissingStub: null,
  );

  @override
  set isInitialized(bool? value) => super.noSuchMethod(
    Invocation.setter(#isInitialized, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logEvent(
    String? eventName,
    Map<String, dynamic>? parameters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [eventName, parameters]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logAdImpression({
    required String? type,
    required String? placement,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAdImpression, [], {
              #type: type,
              #placement: placement,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logAdError({
    required String? errorCode,
    required String? placement,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAdError, [], {
              #errorCode: errorCode,
              #placement: placement,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logExerciseStarted({
    required String? exerciseId,
    required String? from,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logExerciseStarted, [], {
              #exerciseId: exerciseId,
              #from: from,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logExerciseCompleted({
    required String? exerciseId,
    required int? durationSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logExerciseCompleted, [], {
              #exerciseId: exerciseId,
              #durationSeconds: durationSeconds,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSoundPlayed({
    required String? soundId,
    required int? durationSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSoundPlayed, [], {
              #soundId: soundId,
              #durationSeconds: durationSeconds,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSleepEntryAdded() =>
      (super.noSuchMethod(
            Invocation.method(#logSleepEntryAdded, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logFavoriteToggled({
    required String? itemId,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logFavoriteToggled, [], {
              #itemId: itemId,
              #type: type,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logPremiumPurchase({required String? plan}) =>
      (super.noSuchMethod(
            Invocation.method(#logPremiumPurchase, [], {#plan: plan}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logScreenView(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [screenName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserProperty(String? name, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [name, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void printAvailableEvents() => super.noSuchMethod(
    Invocation.method(#printAvailableEvents, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CrashlyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsService extends _i1.Mock
    implements _i5.CrashlyticsService {
  MockCrashlyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  set crashlytics(_i6.FirebaseCrashlytics? value) => super.noSuchMethod(
    Invocation.setter(#crashlytics, value),
    returnValueForMissingStub: null,
  );

  @override
  set isInitialized(bool? value) => super.noSuchMethod(
    Invocation.setter(#isInitialized, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordError(
    dynamic exception,
    StackTrace? stackTrace, {
    String? reason,
    bool? fatal = false,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordError,
              [exception, stackTrace],
              {#reason: reason, #fatal: fatal, #additionalData: additionalData},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordAdError({
    required String? errorType,
    required String? placement,
    required String? errorMessage,
    dynamic originalError,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordAdError, [], {
              #errorType: errorType,
              #placement: placement,
              #errorMessage: errorMessage,
              #originalError: originalError,
              #stackTrace: stackTrace,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordMediaError({
    required String? errorType,
    required String? mediaId,
    required String? errorMessage,
    dynamic originalError,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordMediaError, [], {
              #errorType: errorType,
              #mediaId: mediaId,
              #errorMessage: errorMessage,
              #originalError: originalError,
              #stackTrace: stackTrace,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordNetworkError({
    required String? errorType,
    required String? endpoint,
    required String? errorMessage,
    dynamic originalError,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordNetworkError, [], {
              #errorType: errorType,
              #endpoint: endpoint,
              #errorMessage: errorMessage,
              #originalError: originalError,
              #stackTrace: stackTrace,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordExerciseError({
    required String? errorType,
    required String? exerciseId,
    required String? errorMessage,
    dynamic originalError,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordExerciseError, [], {
              #errorType: errorType,
              #exerciseId: exerciseId,
              #errorMessage: errorMessage,
              #originalError: originalError,
              #stackTrace: stackTrace,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCustomKey(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomKey, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> log(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#log, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> testCrash() =>
      (super.noSuchMethod(
            Invocation.method(#testCrash, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void printAvailableErrorTypes() => super.noSuchMethod(
    Invocation.method(#printAvailableErrorTypes, []),
    returnValueForMissingStub: null,
  );
}
