// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnaAv5XcRjLekFF-1l1Vtb2cmUuOoTUs0',
    appId: '1:703714068680:web:924ef65ba12e8b3d2c3dfd',
    messagingSenderId: '703714068680',
    projectId: 'breathe-flow-app',
    authDomain: 'breathe-flow-app.firebaseapp.com',
    storageBucket: 'breathe-flow-app.firebasestorage.app',
    measurementId: 'G-Z0T69R33E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy6s3IMOWLimfgZ78tHofXkd2Dqs4B_jM',
    appId: '1:703714068680:android:39e181c41ead37ad2c3dfd',
    messagingSenderId: '703714068680',
    projectId: 'breathe-flow-app',
    storageBucket: 'breathe-flow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcyEFvi8XCB2LGR6a4_4CsyzCsuvVa_sM',
    appId: '1:703714068680:ios:a3dd3f812f6b16eb2c3dfd',
    messagingSenderId: '703714068680',
    projectId: 'breathe-flow-app',
    storageBucket: 'breathe-flow-app.firebasestorage.app',
    iosBundleId: 'com.example.breatheFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcyEFvi8XCB2LGR6a4_4CsyzCsuvVa_sM',
    appId: '1:703714068680:ios:a3dd3f812f6b16eb2c3dfd',
    messagingSenderId: '703714068680',
    projectId: 'breathe-flow-app',
    storageBucket: 'breathe-flow-app.firebasestorage.app',
    iosBundleId: 'com.example.breatheFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnaAv5XcRjLekFF-1l1Vtb2cmUuOoTUs0',
    appId: '1:703714068680:web:aeec7ebbdd611f0e2c3dfd',
    messagingSenderId: '703714068680',
    projectId: 'breathe-flow-app',
    authDomain: 'breathe-flow-app.firebaseapp.com',
    storageBucket: 'breathe-flow-app.firebasestorage.app',
    measurementId: 'G-B995DTJZR6',
  );
}
